name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"



[env.production]
name = "cloudflare-docker-proxy"
routes = [
    { pattern = "docker.jsonsong.top", custom_domain = true },
    { pattern = "quay.jsonsong.top", custom_domain = true },
    { pattern = "gcr.jsonsong.top", custom_domain = true },
    { pattern = "k8s-gcr.jsonsong.top", custom_domain = true },
    { pattern = "k8s.jsonsong.top", custom_domain = true },
    { pattern = "ghcr.jsonsong.top", custom_domain = true },
    { pattern = "cloudsmith.jsonsong.top", custom_domain = true },
    { pattern = "ecr.jsonsong.top", custom_domain = true },
    { pattern = "mcr.jsonsong.top", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = "https://registry-1.docker.io"


